image: golang:1.11

stages:
  - build
  - test

build:
  stage: build
  script:
    - go build ./...

test:
  stage: test
  script:
    - test -z "$(gofmt -l . | tee /dev/stderr)"
    - apt-get -qq update
    - apt-get install -y python-pip
    - pip install --user pymorphy2_dicts_ru
    - go test ./...
